### ISSUE TITLE
参数错误

### ISSUE THREAD

**Issue by jvhuaiying** [Enter-tainer/cxx2flow-gui#2]
error[E0423]: expected value, found struct `Dot`
  --> src\main.rs:9:61
   |
9  |     let res = cxx2flow::generate(code.as_bytes(), "", None, Dot);
   |                                                             ^^^
   |
  ::: C:\Users\jvhua\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cxx2flow-0.6.1\src\display\dot.rs:10:1
   |
10 | pub struct Dot {
   | -------------- `Dot` defined here
   |
help: use struct literal syntax instead
   |
9  |     let res = cxx2flow::generate(code.as_bytes(), "", None, Dot { curly: val });
   |                                                             ~~~~~~~~~~~~~~~~~~
help: consider importing this tuple variant instead
   |
4  + use cxx2flow::display::GraphDisplayBackend::Dot;
   |

For more information about this error, try `rustc --explain E0423`.
error: could not compile `app` (bin "app") due to previous error

**Comment by Enter-tainer** [comment]
应该按编译器提示的方法修就行，你可以试一下。或者我明天改一改

**Comment by jvhuaiying** [comment]
> 应该按编译器提示的方法修就行，你可以试一下。或者我明天改一改

明天您看下吧，我这照编译器的提示改一晚上了😂

**Comment by Enter-tainer** [comment]
修好了
